# documentation: https://bluewavelabs.gitbook.io/checkmate
# slogan: Checkmate is an open-source, self-hosted tool designed to track and monitor server hardware, uptime, response times, and incidents in real-time with beautiful visualizations.
# category: monitoring
# tags: monitoring,server,uptime,healthcheck
# logo: svgs/checkmate.png
# port: 52345

services:
  checkmate:
    image: "ghcr.io/bluewave-labs/checkmate-backend-mono:latest"
    restart: always
    environment:
      - SERVICE_FQDN_CHECKMATE_52345
      - "UPTIME_APP_CLIENT_HOST=${SERVICE_FQDN_CHECKMATE}"
      - "UPTIME_APP_API_BASE_URL=${SERVICE_URL_CHECKMATE}/api/v1"
      - "DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db"
      - "CLIENT_HOST=${SERVICE_FQDN_CHECKMATE}"
      - "JWT_SECRET=${SERVICE_PASSWORD_CHECKMATE}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
  mongodb:
    image: "ghcr.io/bluewave-labs/checkmate-mongo:latest"
    restart: always
    command:
      - mongod
      - "--quiet"
      - "--bind_ip_all"
    volumes:
      - "checkmate_mongo_data:/data/db"
    healthcheck:
      test:
        - CMD
        - mongosh
        - "--eval"
        - "db.adminCommand('ping')"
        - "--quiet"
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
  capture:
    image: ghcr.io/bluewave-labs/capture:latest
    restart: unless-stopped
    environment:
      - "API_SECRET=${SERVICE_BASE64_64_CAPTURE}"
    volumes:
      - /etc/os-release:/etc/os-release:ro
volumes:
  checkmate_mongo_data: null
